# Site Configuration
[site]
name = "joosyjools"
domain = "joosyjools.com"
base_url = "https://joosyjools.com"
content_dir = "content"
created_at = 2025-06-28T08:21:06-04:00
updated_at = 2025-06-28T08:21:06-04:00

# Content Types
[[content_types]]
name = "page"
[[content_types]]
name = "post"
