# Site Configuration
[site]
id = "3123123123"
name = "joosyjools"
domain = "joosyjools.com"
base_url = "https://joosyjools.com"
content_dir = "content"
created_at = 2025-06-28T08:21:06-04:00
updated_at = 2025-06-28T08:21:06-04:00

# Design System Configuration
[design]
theme = "default"
mode = "light"

# Theme Tokens
[design.tokens.colors]
primary = "oklch(69% 0.17 162.48)"
primary_content = "oklch(97% 0.021 166.113)"
secondary = "oklch(39% 0.095 152.535)"
secondary_content = "oklch(94% 0.028 342.258)"
accent = "oklch(62% 0.214 259.815)"
accent_content = "oklch(97% 0.014 254.604)"
neutral = "oklch(27% 0.006 286.033)"
neutral_content = "oklch(98% 0.001 106.423)"
base_100 = "oklch(100% 0 0)"
base_200 = "oklch(95% 0.01 150)"
base_300 = "oklch(90% 0.02 150)"
base_content = "oklch(15% 0.03 150)"
info = "oklch(70% 0.165 254.624)"
info_content = "oklch(28% 0.091 267.935)"
success = "oklch(84% 0.238 128.85)"
success_content = "oklch(27% 0.072 132.109)"
warning = "oklch(75% 0.183 55.934)"
warning_content = "oklch(26% 0.079 36.259)"
error = "oklch(71% 0.194 13.428)"
error_content = "oklch(27% 0.105 12.094)"

[design.tokens.spacing]
selector = "0.5rem"
field = "0.25rem"
base = "1rem"
sm = "0.5rem"
md = "1.5rem"
lg = "2rem"
xl = "3rem"

[design.tokens.typography]
font_sans = "Inter, system-ui, sans-serif"
font_mono = "JetBrains Mono, Roboto Mono, monospace"
font_serif = "Georgia, serif"

[design.tokens.borders]
width = "1px"
radius_selector = "0.5rem"
radius_field = "0.25rem"
radius_box = "0.25rem"

[design.tokens.shadows]
base = "0 1px 3px rgba(0,0,0,0.1)"
sm = "0 1px 2px rgba(0,0,0,0.05)"
md = "0 4px 6px rgba(0,0,0,0.1)"
lg = "0 10px 15px rgba(0,0,0,0.1)"
xl = "0 20px 25px rgba(0,0,0,0.1)"

# Content Types
[[content_types]]
name = "page"
[[content_types]]
name = "post"
