# Theme Configuration
name = "default"
base = "light"
version = "1.0.0"

[tokens.colors]
primary = "oklch(69% 0.17 162.48)"
primary_content = "oklch(97% 0.021 166.113)"
secondary = "oklch(39% 0.095 152.535)" 
secondary_content = "oklch(94% 0.028 342.258)"
accent = "oklch(62% 0.214 259.815)"
accent_content = "oklch(97% 0.014 254.604)"
neutral = "oklch(27% 0.006 286.033)"
neutral_content = "oklch(98% 0.001 106.423)"
base_100 = "oklch(100% 0 0)"
base_200 = "oklch(95% 0.01 150)"
base_300 = "oklch(90% 0.02 150)"
base_content = "oklch(15% 0.03 150)"
info = "oklch(70% 0.165 254.624)"
info_content = "oklch(28% 0.091 267.935)"
success = "oklch(84% 0.238 128.85)"
success_content = "oklch(27% 0.072 132.109)"
warning = "oklch(75% 0.183 55.934)"
warning_content = "oklch(26% 0.079 36.259)"
error = "oklch(71% 0.194 13.428)"
error_content = "oklch(27% 0.105 12.094)"

[tokens.spacing]
selector = "0.5rem"
field = "0.25rem"
base = "1rem"
sm = "0.5rem"
md = "1.5rem"
lg = "2rem"
xl = "3rem"

[tokens.typography]
font_sans = "Inter, system-ui, sans-serif"
font_mono = "JetBrains Mono, Roboto Mono, monospace"
font_serif = "Georgia, serif"

[tokens.borders]
width = "1px"
radius_selector = "0.5rem"
radius_field = "0.25rem"
radius_box = "0.25rem"
